apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jdafda-123-poi-map-app-dev
  annotations:
    argocd/app-name: jdafda-123-poi-map-app-dev
    backstage.io/kubernetes-id: jdafda-123-poi-map-app
    backstage.io/kubernetes-namespace: jdafda-123
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/jdafda-123-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/jdafda-123/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/jdafda-123/deployments/jdafda-123-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/jdafda-123-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://jdafda-123-poi-map-app-jdafda-123.apps.rosa916.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/jdafda"
  system: workshop-system-jdafda-123
  consumesApis:
    - gateway-api-jdafda-123
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-jdafda-123
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/jdafda"
